### PR TITLE
Add building:part to preset fields

### PR DESCRIPTION
**Pull request by LucasLarson**
Adding a frequently used key to the autocomplete presets

### CODE REVIEW

**Comment by wtimme** [comment]
Thanks for your contribution!

I don't have a strong opinion against merging this. The only thing that I am contemplating is whether this preset (that no doubt adds some value for you) might get overwritten the next time we sync this JSON file with the one from [iD][1].

From the [Git history of that file][2] it looks like the guys over at the iD repository are pretty quick with merging, so it might be more sustainable to try to get them to add it to their fields.json file.

What do you think - should we take the risk or rather ask them to add this to the "official" list of presets?

[1]: https://github.com/openstreetmap/iD/blob/2.x/data/presets/fields.json
[2]: https://github.com/openstreetmap/iD/commits/2.x/data/presets/fields.json

**Comment by LucasLarson** [comment]
Wow — I didn’t know GoMap or Completionist well enough to realize we weren’t generating that part of it ourselves. I should definitely propose this at iD instead. Thank you!

I couldn’t read from the repo where this ever gets updated though… does it?

**Comment by wtimme** [comment]
You're correct, it only gets updated manually, which hasn't happened in a while. I've created an issue (#34) to change this.

Since that is the case, I think we can merge this without problems for now. Thanks for your contribution!

**Comment by wtimme** [comment]
Hey LucasLarson,

I just merged the latest changes from bryceco/GoMap, I had a merge conflict in the `presets.json` file. With bryceco/GoMap#260, @bryceco updated the `presets.json` file, and the format of the file had changed completely.

I resolved the merge conflict in a way that **includes** your changes, but maybe it'd be a good idea to contact the _iD_ maintainers with your preset suggestion. Just FYI. :)

**Pull request merged**
